spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwdb?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhapeng213.
  redis:
    host: localhost
    database: 1
    port: 6379
    password:
    timeout: 300ms