server:
  port: 8048
  address: 0.0.0.0
spring:
  profiles:
    active: local
  application:
    name: scg-scaffold-service
    open-in-view: true
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:dao/*.xml

redis:
  database: 1
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: scaffold-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /api/v1/druid/**
      - /api/v1/admin/login
      - /api/v1/admin/register
      - /api/v1/admin/info
      - /api/v1/admin/logout
      - /api/v1/health/**